name: Build and deploy
'on':
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Use Bun 1.0.14
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.14
      - name: Install deps
        run: bun install
      - name: Build
        run: bun run build
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_BASE64" | base64 --decode > firebase-service-account.json
          bun run firebase deploy --project $FIREBASE_PROJECT
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
