name: Build and deploy
'on':
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: Dabolus/deploy-firebase@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
